# Generated by Django 4.2.4 on 2023-08-15 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Equipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("equipment_name", models.CharField(max_length=250)),
                ("equipment_description", models.TextField()),
                ("equipment_image", models.ImageField(upload_to="images/")),
                ("equipment_price", models.IntegerField()),
                (
                    "equipment_status",
                    models.CharField(
                        choices=[
                            ("available", "AVAILABLE"),
                            ("unavailable", "UNAVAILABLE"),
                            ("pending", "PENDING"),
                        ],
                        max_length=250,
                    ),
                ),
                ("equipment_quantity", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Manufacturer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("manufacturer_name", models.CharField(max_length=250)),
                ("manufacturer_description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_date", models.DateTimeField(auto_now_add=True)),
                ("return_date", models.DateTimeField()),
                ("quantity", models.PositiveIntegerField()),
                ("address", models.TextField()),
                (
                    "equipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="equipment.equipment",
                    ),
                ),
            ],
        ),
    ]
